/** Mirrors web `global_sponsor_hub-fe/src/data/skills.ts` for consistent employer search / filtering. */

export type SkillsData = {
  [category: string]: string[];
};

export const SKILLS_DATA: SkillsData = {
  "Technology & Digital Skills": [
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "PHP",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "TypeScript",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Next.js",
    "Laravel",
    "Django",
    "Spring Boot",
    ".NET",
    "REST APIs",
    "GraphQL",
    "SQL",
    "NoSQL",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "DevOps",
    "Linux",
    "Cybersecurity",
    "Blockchain",
    "Web3",
    "AI / Machine Learning",
    "Data Science",
    "Big Data",
    "Power BI",
    "Tableau",
  ],
  "Design & Creative Skills": [
    "UI Design",
    "UX Design",
    "Product Design",
    "Graphic Design",
    "Motion Design",
    "Branding",
    "Typography",
    "Illustration",
    "Figma",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe XD",
    "After Effects",
    "Video Editing",
    "3D Modelling",
    "Animation",
  ],
  "Marketing, Sales & Growth Skills": [
    "Digital Marketing",
    "SEO",
    "SEM",
    "Google Ads",
    "Facebook Ads",
    "Content Marketing",
    "Email Marketing",
    "Social Media Marketing",
    "Influencer Marketing",
    "Brand Strategy",
    "Marketing Analytics",
    "Copywriting",
    "Sales Strategy",
    "B2B Sales",
    "B2C Sales",
    "Lead Generation",
    "CRM (Salesforce, HubSpot)",
    "Account Management",
    "Negotiation",
  ],
  "Business, Management & Operations Skills": [
    "Project Management",
    "Product Management",
    "Agile",
    "Scrum",
    "Kanban",
    "Business Analysis",
    "Strategic Planning",
    "Operations Management",
    "Process Improvement",
    "Change Management",
    "Stakeholder Management",
    "Risk Management",
    "OKRs",
    "Leadership",
    "Team Management",
  ],
  "Finance, Legal & Admin Skills": [
    "Financial Analysis",
    "Accounting",
    "Bookkeeping",
    "Auditing",
    "Budgeting",
    "Forecasting",
    "Taxation",
    "Payroll",
    "Financial Modelling",
    "Compliance",
    "Contract Management",
    "Legal Research",
    "Corporate Law",
    "Company Secretarial",
  ],
  "Healthcare & Science Skills": [
    "Clinical Research",
    "Nursing",
    "Patient Care",
    "Medical Coding",
    "Healthcare Administration",
    "Public Health",
    "Laboratory Analysis",
    "Biotechnology",
    "Pharmaceutical Research",
    "Quality Assurance (QA)",
  ],
  "Engineering & Technical Skills": [
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Structural Engineering",
    "Industrial Engineering",
    "Mechatronics",
    "Robotics",
    "CAD",
    "AutoCAD",
    "SolidWorks",
    "Quality Control",
    "Lean Manufacturing",
  ],
  "Human Resources & People Skills": [
    "Recruitment",
    "Talent Acquisition",
    "Employer Branding",
    "Performance Management",
    "HR Operations",
    "Employee Engagement",
    "Learning & Development",
    "Payroll Management",
    "HR Analytics",
  ],
  "Soft Skills (Highly Recommended)": [
    "Communication",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Emotional Intelligence",
    "Conflict Resolution",
    "Decision Making",
  ],
};

export function getAllSkillsSorted(): string[] {
  return Array.from(new Set(Object.values(SKILLS_DATA).flat())).sort((a, b) => a.localeCompare(b));
}
